version: '3'
services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=auth-user
      - POSTGRESQL_PASSWORD=auth-password
      - POSTGRESQL_DATABASE=auth-db
      - POSTGRESQL_PORT_NUMBER=5433
    ports:
      - "5433:5433"
    networks:
      - crnt-4
      
  pg-up-checker:
    image: oliosinter/ansible-probe:1.0.0
    environment:
      PROBE_HOST: postgres
      PROBE_PORT: 5433
      PROBE_TIMEOUT: 20
    command: [ "probe.yml" ]
    networks:
      - crnt-4

networks:
  crnt-4:
    external: true
