version: '3'
services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=auth-user
      - POSTGRESQL_PASSWORD=auth-password
      - POSTGRESQL_DATABASE=auth-db
    ports:
      - "5432:5432"

  pg-up-checker:
    image: oliosinter/ansible-probe:1.0.0
    environment:
      PROBE_HOST: postgres
      PROBE_PORT: 5432
      PROBE_TIMEOUT: 20
    command: [ "probe.yml" ]