name: build-and-test
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
          cache: true
      - name: Install dependencies
        run: |
          go get github.com/Masterminds/squirrel@v1.5.3
          go get github.com/aead/chacha20poly1305@v0.0.0-20170617001512-233f39982aeb
          go get github.com/google/uuid@v1.3.0
          go get github.com/grpc-ecosystem/grpc-gateway/v2@v2.15.2
          go get github.com/joho/godotenv@v1.4.0
          go get github.com/lib/pq@v1.10.7
          go get github.com/o1egl/paseto@v1.0.0
          go get github.com/sirupsen/logrus@v1.9.0
          go get go.uber.org/zap@v1.24.0
          go get google.golang.org/genproto@v0.0.0-20230223222841-637eb2293923
          go get google.golang.org/grpc@v1.53.0
          go get google.golang.org/protobuf@v1.28.1
      - name: Build
        run: go build -o ./bin/crnt-auth-service ./cmd/crnt-auth-service/main.go
      - name: Test with the Go CLI
        run: |
          go test ./internal/pkg/...